name: OnJoin
main: darknesspl\OnJoin\OnJoin
author: darknesspl
version: 1.1.0
api: 5.0.0
description:  a simple plugin that causes that when a player leaves or quits, a message will appear saying that he joined just as he left
permissions:
  onjoin.config:
    default: op
